[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "export ELM_HOME=\"elm-stuff\" && tar -xzf elm-cache.tar.gz && && mv -f .elm $HOME && ls $HOME/.elm/0.19.1 && npm run build"

[[plugins]]
  package = "netlify-plugin-cache"
    [plugins.inputs]
      paths = ["elm-stuff", "$HOME/.elm"]
